apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: non-root-pod
  name: non-root-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: non-root-pod
    resources: {}
    securityContext:
      runAsNonRoot: true #Remove the root privileges over the container
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
