apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: default-pod
  name: default-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: sh
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: different-user-and-groups-pod
  name: different-user-and-groups-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: sh
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
