apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: privileged-pod
  name: privileged-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: privileged-pod
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true # Allow process gain more priviledge than the parent.
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
