apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-privilege-escalation-pod
  name: pod-privilege-escalation-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: pod-privilege-escalation-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
