apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    #rootNamespace: istio-system
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  components:
    base:
      enabled: true
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
    pilot:
      enabled: true
  hub: docker.io/istio
  profile: default
  tag: 1.21.0
  values:
    defaultRevision: ""
    gateways:
      istio-egressgateway: {}
      istio-ingressgateway: {}
    global:
      configValidation: true
      istioNamespace: istio-system

