apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kuard-tls
  name: kuard-tls
spec:
  containers:
  - image: gcr.io/kuard-demo/kuard-amd64:blue
    name: kuard-tls
    volumeMounts:
    - name: tls-certs
      mountPath: "/tls"
      readOnly: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls
status: {}
