apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-volume
  name: pod-volume
spec:
  containers:
  - image: nginx
    name: pod-volume
    resources: {}
    # Start: Mount Volume
    volumeMounts:
    - mountPath: /data
      name: test
    # End: Mount Volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  # Start: Volume Definition
  volumes:
  - name: test
    emptyDir: {}
  # End: Volume Definition
status: {}
