apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-cm
  name: sample-cm
spec:
  containers:
  - image: nginx
    name: sample-cm
    resources: {}
    # Start: Mount Volume
    volumeMounts:
    - mountPath: /data
      name: cm-volume
    # End: Mount Volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  # Start: Volume Definition from CM
  volumes:
  - name: cm-volume
    configMap:
      name: cm-test
  # End: Volume Definition from CM
status: {}
