apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: MyNginx
  name: MyNginx
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  initContainers:
    - name: ubuntu-container
      image: ubuntu
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command: ["/bin/sh"]
      args: ["-c", "date >> /pod-data/index.html"]
  containers:
    - image: nginx
      name: MyNginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
