apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: initexample
  name: initexample
spec:
  containers:
  - image: ngnix
    name: main
    resources: {}
  # Start: Init containers
  initContainers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: initexample
    resources: {}
  # End: Init containers
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
