apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "sleep-policy"
  namespace: "peer-authorization"
spec:
  selector:
    matchLabels:
      run: sleep
  mtls:
    mode: STRICT
