apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-without-shell
  name: pod-without-shell
spec:
  containers:
  - image: httpd
    name: pod-without-shell
    resources: {}
    startupProbe:
      exec:
        command:
        - rm
        - /bin/bash
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
