apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: seccomp-pod
  name: seccomp-pod
spec:
  securityContext: # add
    seccompProfile: # add
      type: Localhost # add
      localhostProfile: profiles/audit.json # add
  containers:
  - image: nginx
    name: seccomp-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
