apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: read-only-fs-pod
  name: read-only-fs-pod
spec:
  containers:
  - image: httpd
    name: read-only-fs-pod
    resources: {}
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
        - name: httpd-logs
          mountPath: /usr/local/apache2/logs
  volumes:
    - name: httpd-logs
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
