apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx # Change label name from `app` to something else to fail
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      securityContext:
        runAsNonRoot: false # Change to `true` to pass
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
