apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ingress
  labels:
    namespace: ingress
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-app-v1
  name: nginx-app-v1
  namespace: ingress
spec:
  volumes:
  - name: html
    emptyDir: {}
  initContainers:
  - name: init
    image: busybox
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    command: ['sh', '-c', 'echo "Welcome to: $(MY_POD_NAME)" > /usr/share/nginx/html/index.html']
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  containers:
  - image: nginx
    name: nginx-app
    resources: {}
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx-app-v1
  name: nginx-app-v1
  namespace: ingress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-app-v1