apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: rbac-practice
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ulisesmx-role
  namespace: rbac-practice
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ulises-role-binding
  namespace: rbac-practice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ulisesmx-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ulisesmx
