apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mynginx
  name: mynginx
spec:
  containers:
  - image: nginx
    name: mynginx
    resources:
      requests:
        cpu: "0.25"
        memory: 250Mi
      limits:
        cpu: "0.5"
        memory: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
