apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: traffic-shifting
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-app
    version: v1
  name: nginx-app-v1
  namespace: traffic-shifting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-app
        version: v1
    spec:
      volumes:
      - name: html
        emptyDir: {}
      initContainers:
      - name: init
        image: busybox
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ['sh', '-c', 'echo "Welcome to: $(MY_POD_NAME)" > /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      containers:
      - image: nginx
        name: nginx-app
        resources: {}
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-app
    version: v2
  name: nginx-app-v2
  namespace: traffic-shifting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
      version: v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-app
        version: v2
    spec:
      volumes:
      - name: html
        emptyDir: {}
      initContainers:
      - name: init
        image: busybox
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ['sh', '-c', 'echo "Welcome to: $(MY_POD_NAME)" > /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      containers:
      - image: nginx
        name: nginx-app
        resources: {}
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-app
  name: nginx-app
  namespace: traffic-shifting
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app
