apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kuard
  name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
