apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: restricted
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: myquota
  namespace: restricted
spec:
  hard:
    memory: 1G
    cpu: "2"
    pods: "3"
status: {}
