apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: disable-sa
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: disable-in-pod
  namespace: disable-sa
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: disable-in-pod
  name: disable-in-pod
  namespace: disable-sa
spec:
  serviceAccountName: disable-in-pod
  automountServiceAccountToken: false
  containers:
  - image: nginx
    name: disable-in-sa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: enable-sa
  name: enable-sa
  namespace: disable-sa
spec:
  containers:
  - image: nginx
    name: enable-sa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
