apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sTrustedImage
metadata:
  name: pod-must-have-trusted-image
  namespace: default
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
