apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: gvisor 
handler: runsc
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: custom-rtc-pod
  name: custom-rtc-pod
spec:
  runtimeClassName: gvisor
  containers:
  - image: nginx
    name: custom-rtc-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
