apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-app-vs
  namespace: traffic-routing
spec:
  hosts:
  - nginx-app
  http:
  - route:
    - destination:
        host: nginx-app
        subset: v1
